<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[taken screenshot]]>
    </line>
    <line>
      <![CDATA[mymethod3 is running]]>
    </line>
    <line>
      <![CDATA[test Passed Successful]]>
    </line>
    <line>
      <![CDATA[mymethod1 is running]]>
    </line>
    <line>
      <![CDATA[test Passed Successful]]>
    </line>
    <line>
      <![CDATA[this test is skipped]]>
    </line>
  </reporter-output>
  <suite started-at="2022-07-04T16:21:12 IST" name="Default suite" finished-at="2022-07-04T16:21:12 IST" duration-ms="52">
    <groups>
    </groups>
    <test started-at="2022-07-04T16:21:12 IST" name="Default test" finished-at="2022-07-04T16:21:12 IST" duration-ms="52">
      <class name="listenerStudy.Testclass">
        <test-method signature="mymethod2()[pri:0, instance:listenerStudy.Testclass@41e36e46]" started-at="2022-07-04T16:21:12 IST" name="mymethod2" finished-at="2022-07-04T16:21:12 IST" duration-ms="11" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at listenerStudy.Testclass.mymethod2(Testclass.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[taken screenshot]]>
            </line>
          </reporter-output>
        </test-method> <!-- mymethod2 -->
        <test-method signature="mymethod3()[pri:0, instance:listenerStudy.Testclass@41e36e46]" started-at="2022-07-04T16:21:12 IST" name="mymethod3" finished-at="2022-07-04T16:21:12 IST" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[mymethod3 is running]]>
            </line>
            <line>
              <![CDATA[test Passed Successful]]>
            </line>
          </reporter-output>
        </test-method> <!-- mymethod3 -->
        <test-method signature="mymethod1()[pri:0, instance:listenerStudy.Testclass@41e36e46]" started-at="2022-07-04T16:21:12 IST" name="mymethod1" finished-at="2022-07-04T16:21:12 IST" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[mymethod1 is running]]>
            </line>
            <line>
              <![CDATA[test Passed Successful]]>
            </line>
          </reporter-output>
        </test-method> <!-- mymethod1 -->
        <test-method signature="mymethod4()[pri:0, instance:listenerStudy.Testclass@41e36e46]" started-at="2022-07-04T16:21:12 IST" name="mymethod4" finished-at="2022-07-04T16:21:12 IST" depends-on-methods="listenerStudy.Testclass.mymethod2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Testclass.mymethod4()[pri:0, instance:listenerStudy.Testclass@41e36e46] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Testclass.mymethod4()[pri:0, instance:listenerStudy.Testclass@41e36e46] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[this test is skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- mymethod4 -->
      </class> <!-- listenerStudy.Testclass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
